version: "3.8"
services:
  spark-master:
    image: "spark-master"
    hostname: spark-master
    environment:
      SPARK_CONF_DIR: /conf
    ports:
      - 8080:8080
      - 4040:4040
      - 6066:6066
      - 7077:7077
    networks:
      - stream-tweets
    deploy:
      placement:
        constraints: [node.labels.role==master]
  spark-worker:
    image: spark-worker
    hostname: spark-worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
    depends_on:
      - master
    ports:
      - "8081:8081"
    deploy:
      placement:
        constraints: [node.labels.role==worker]
        max_replicas_per_node: 1
      replicas: 2
    networks:
      - stream-tweets
networks:
  stream-tweets:
    external:
      name: stream-tweets