version: "3.8"
services:
  spark-master:
    image: "sdesilva26/spark_master:0.0.2"
    ports:
      - "8080:8080"
    networks:
      - stream-tweets
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints: [node.labels.role==master]
  spark-worker:
    image: "sdesilva26/spark_worker:0.0.2"
    ports:
      - "8081:8081"
    environment:
      - CORES=2
      - MEMORY=8G
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints: [node.labels.role==worker]
        max_replicas_per_node: 1
      replicas: 2
    networks:
      - stream-tweets
networks:
  stream-tweets:
    external:
      name: stream-tweets